language: python
python:
  - "3.7"
# command to install dependencies


install:
  - pip install -U setuptools
  - pip install pywikibot
  - pip install openpyxl
# command to run tests
branches:
    only:
        - dev

script:
  - python -m unittest -v

