language: python
python:
  - "3.8"
# command to install dependencies


install:
  - pip install -U setuptools
  - pip install pywikibot
  - pip install pandas
  - pip install mwparserfromhell>=0.5.0
# command to run tests
branches:
    only:
        - dev

script:
  - python -m unittest -v

