# -*- coding: utf-8 -*-

def load():
    #no fr and en  managed already
    return ["aa", "ab", "ace", "ady", "ady-cyrl", "aeb", 
            "aeb-arab", "aeb-latn", "af", "ak", "aln", "am", 
            "an", "ang", "anp", "ar", "arc", "arn", 
            "arq", "ary", "arz", "as", "ast", "atj", 
            "awa", "av", "avk", "ay", "az", "azb", "ba", 
            "ban", "bar", "bbc", "bbc-latn", "bcc", "bcl", 
            "be", "be-tarask", "bg", "bgn", "bho", "bi", 
            "bjn", "bm", "bn", "bo", "bpy", "bqi", "br", 
            "brh", "bs", "bto", "bug", "bxr", "ca", "cbk-zam", 
            "cdo", "ce", "ceb", "ch", "cho", "chr", "chy", "ckb",
            "co", "cps", "cr", "crh-latn", "crh-cyrl", "cs", "csb",
            "cu", "cv", "cy", "da", "de", "de-at", "de-ch", "din", 
            "diq", "dsb", "dtp", "dty", "dv", "dz", "ee", "egl", "el",
            "eml", "en-ca", "en-gb", "eo", "es", "et", "eu", 
            "ext", "fa", "ff", "fi", "fit", "fj", "fo", "frc",
            "frp", "frr", "fur", "fy", "ga", "gag", "gan", "gan-hans",
            "gan-hant", "gd", "gl", "glk", "gn", "gom", "gom-deva", 
            "gom-latn", "gor", "got", "grc", "gsw", "gu", "gv", "ha",
            "hak", "haw", "he", "hi", "hif", "hif-latn", "hil", "ho", 
            "hr", "hrx", "hsb", "ht", "hu", "hy", "hz", "ia", "id", 
            "ie", "ig", "ii", "ik", "ike-cans", "ike-latn", "ilo", 
            "inh", "io", "is", "it", "iu", "ja", "jam", "jbo", "jut",
            "jv", "ka", "kaa", "kab", "kbd", "kbd-cyrl", "kbp", "kea",
            "kg", "khw", "ki", "kiu", "kj", "kk", "kk-arab", "kk-cyrl", 
            "kk-latn", "kk-cn", "kk-kz", "kk-tr", "kl", "km", "kn", "ko",
            "ko-kp", "koi", "kr", "krc", "kri", "krj", "krl", "ks",
            "ks-arab", "ks-deva", "ksh", "ku", "ku-latn", "ku-arab", 
            "kv", "kw", "ky", "la", "lad", "lb", "lbe", "lez", "lfn", 
            "lg", "li", "lij", "liv", "lki", "lmo", "ln", "lo", "loz", 
            "lrc", "lt", "ltg", "lus", "luz", "lv", "lzh", "lzz", "mai",
            "map-bms", "mdf", "mg", "mh", "mhr", "mi", "min", "mk", "ml",
            "mn", "mo", "mr", "mrj", "ms", "mt", "mus", "mwl", "my", 
            "myv", "mzn", "na", "nah", "nan", "nap", "nb", "nds", "nds-nl",
            "ne", "new", "ng", "niu", "nl", "nn", "nod", "nov", "nrm", 
            "nso", "nv", "ny", "nys", "oc", "olo", "om", "or", "os", "ota",
            "pa", "pag", "pam", "pap", "pcd", "pdc", "pdt", "pfl", "pi",
            "pih", "pl", "pms", "pnb", "pnt", "prg", "ps", "pt", "pt-br",
            "qu", "qug", "rgn", "rif", "rm", "rmy", "rn", "ro", "roa-tara",
            "ru", "rue", "rup", "ruq", "ruq-cyrl", "ruq-latn", "rw", "rwr",
            "sa", "sah", "sat", "sc", "scn", "sco", "sd", "sdc", "sdh", 
            "se", "sei", "ses", "sg", "sgs", "sh", "shi", "shi-tfng", 
            "shi-latn", "shn", "si", "sje", "sk", "sl", "sli", "sm", "sma", 
            "smj", "sn", "so", "sq", "sr", "sr-ec", "sr-el", "srn", "srq", 
            "ss", "st", "stq", "su", "sv", "sw", "szl", "ta", "tcy", 
            "te", "tet", "tg", "tg-cyrl", "tg-latn", "th", "ti", "tk",
            "tl", "tly", "tn", "to", "tpi", "tr", "tru", "ts", "tt", 
            "tt-cyrl", "tt-latn", "tum", "tw", "ty", "tyv", "udm", "ug",
            "ug-arab", "ug-latn", "uk", "ur", "uz", "ve", "vec", "vep", 
            "vi", "vls", "vmf", "vo", "vot", "vro", "wa", "war", "wo",
            "wuu", "xal", "xh", "xmf", "yi", "yo", "yue", "za", "zea",
            "zh", "zh-cn", "zh-hans", "zh-hant", "zh-hk", "zh-mo", "zh-my",
            "zh-sg", "zh-tw", "zu"]
